[package]
name = "ssss-rs-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssss-rs-core = { path = "../ssss-rs-core"}
structopt = "0.3.26"
