[workspace]
members = [
    "ssss-rs-core",
    "ssss-rs-cli"
]
resolver = "3"

[workspace.package]
version = "0.3.0"
authors = ["Wampie Driessen <wampiedriessen@gmail.com>"]
edition = "2024"
