name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check
      run: cargo check --release
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release

